### Creation of Matrix

In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [2]:
M = np.array([[3,4],[2,8],[1,9]])

In [3]:
M

array([[3, 4],
       [2, 8],
       [1, 9]])

In [4]:
M.shape

(3, 2)

In [5]:
M.min()

1

In [6]:
M.size

6

In [7]:
v = np.array([4,6,5,3,1,7,6,3])


In [8]:
v.size

8

In [9]:
v.reshape(4,2)

array([[4, 6],
       [5, 3],
       [1, 7],
       [6, 3]])

In [10]:
v.reshape(2,4)

array([[4, 6, 5, 3],
       [1, 7, 6, 3]])

In [11]:
v.reshape(1,8)

array([[4, 6, 5, 3, 1, 7, 6, 3]])

In [12]:
v.reshape(8,1)

array([[4],
       [6],
       [5],
       [3],
       [1],
       [7],
       [6],
       [3]])

In [13]:
M.dtype

dtype('int32')

In [14]:
M = np.array(([[3,4],[2,8],[1,9]]),dtype=np.int8)

In [15]:
M

array([[3, 4],
       [2, 8],
       [1, 9]], dtype=int8)

In [16]:
M = np.array([[3,4,8,0],[2,8,1,3],[1,9,5,6]],dtype=np.int8)

In [17]:
M

array([[3, 4, 8, 0],
       [2, 8, 1, 3],
       [1, 9, 5, 6]], dtype=int8)

In [18]:
M.flatten()

array([3, 4, 8, 0, 2, 8, 1, 3, 1, 9, 5, 6], dtype=int8)

In [19]:
M.reshape(3,-1)

array([[3, 4, 8, 0],
       [2, 8, 1, 3],
       [1, 9, 5, 6]], dtype=int8)

In [20]:
M.reshape(2,-1)

array([[3, 4, 8, 0, 2, 8],
       [1, 3, 1, 9, 5, 6]], dtype=int8)

In [21]:
M.reshape(-1,2)

array([[3, 4],
       [8, 0],
       [2, 8],
       [1, 3],
       [1, 9],
       [5, 6]], dtype=int8)

In [22]:
M.reshape(-1)

array([3, 4, 8, 0, 2, 8, 1, 3, 1, 9, 5, 6], dtype=int8)

### Matrix Operations

In [23]:
M

array([[3, 4, 8, 0],
       [2, 8, 1, 3],
       [1, 9, 5, 6]], dtype=int8)

In [24]:
for row in M:
    print(row)

[3 4 8 0]
[2 8 1 3]
[1 9 5 6]


In [25]:
for row in M:
    for value in row:
        print(value, end =' ')
    print()

3 4 8 0 
2 8 1 3 
1 9 5 6 


In [26]:
for row in M:
    print(*row)

3 4 8 0
2 8 1 3
1 9 5 6


### Addition

In [27]:
M1 = np.array([[4,5,6],[2,1,9],[0,2,8]])
M2 = np.array([[2,5,7],[0,8,7],[6,4,3]])

In [28]:
M3 = M1 + M2

In [29]:
M3

array([[ 6, 10, 13],
       [ 2,  9, 16],
       [ 6,  6, 11]])

### Subtraction

In [30]:
M3 = M1 - M2

In [31]:
M3

array([[ 2,  0, -1],
       [ 2, -7,  2],
       [-6, -2,  5]])

## Scaler Multiplication

In [32]:
M1, M1 * 2

(array([[4, 5, 6],
        [2, 1, 9],
        [0, 2, 8]]),
 array([[ 8, 10, 12],
        [ 4,  2, 18],
        [ 0,  4, 16]]))

In [33]:
M1 + 10

array([[14, 15, 16],
       [12, 11, 19],
       [10, 12, 18]])

In [34]:
M3 = 2* (M1 + M2)

In [35]:
M4 = 2* M1 + 2 * M2

In [36]:
M3,M4

(array([[12, 20, 26],
        [ 4, 18, 32],
        [12, 12, 22]]),
 array([[12, 20, 26],
        [ 4, 18, 32],
        [12, 12, 22]]))

In [37]:
M3=M1 * (2+3)

In [38]:
M3

array([[20, 25, 30],
       [10,  5, 45],
       [ 0, 10, 40]])

In [39]:
M4 = M1 * 2 + 3 * M1

In [40]:
M4

array([[20, 25, 30],
       [10,  5, 45],
       [ 0, 10, 40]])

In [41]:
1 * M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [42]:
-1 * M1

array([[-4, -5, -6],
       [-2, -1, -9],
       [ 0, -2, -8]])

## Matrix Multiplication

In [43]:
M1,M2

(array([[4, 5, 6],
        [2, 1, 9],
        [0, 2, 8]]),
 array([[2, 5, 7],
        [0, 8, 7],
        [6, 4, 3]]))

In [44]:
M1 * M2

array([[ 8, 25, 42],
       [ 0,  8, 63],
       [ 0,  8, 24]])

In [45]:
M1 @ M2

array([[44, 84, 81],
       [58, 54, 48],
       [48, 48, 38]])

In [46]:
M1 @ M2

array([[44, 84, 81],
       [58, 54, 48],
       [48, 48, 38]])

In [47]:
M2 @ M1

array([[ 18,  29, 113],
       [ 16,  22, 128],
       [ 32,  40,  96]])

In [48]:
M3

array([[20, 25, 30],
       [10,  5, 45],
       [ 0, 10, 40]])

In [49]:
M1 @ (M2 @ M3), (M1 @ M2) @ M3

(array([[1720, 2330, 8340],
        [1700, 2200, 6090],
        [1440, 1820, 5120]]),
 array([[1720, 2330, 8340],
        [1700, 2200, 6090],
        [1440, 1820, 5120]]))

In [50]:
M1 @ (M2 + M3) 

array([[174, 269, 666],
       [108, 199, 513],
       [ 68, 138, 448]])

In [51]:
(M1 @ M2) + (M1 @ M3)

array([[174, 269, 666],
       [108, 199, 513],
       [ 68, 138, 448]])

In [52]:
np.matmul(M1,M2)

array([[44, 84, 81],
       [58, 54, 48],
       [48, 48, 38]])

In [53]:
(M1 + M2) @ M3 

array([[ 220,  330, 1150],
       [ 130,  255, 1105],
       [ 180,  290,  890]])

In [54]:
(M1 @ M3) + (M2 @ M3)

array([[ 220,  330, 1150],
       [ 130,  255, 1105],
       [ 180,  290,  890]])

### Matrix Transpose

In [55]:
M1.T

array([[4, 2, 0],
       [5, 1, 2],
       [6, 9, 8]])

In [56]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [57]:
np.transpose(M1)

array([[4, 2, 0],
       [5, 1, 2],
       [6, 9, 8]])

In [58]:
import numpy as np
row = int(input("Enter number of rows:"))
col = int(input("Enter number of col:"))
mat = np.zeros(row * col , dtype = np.int16)
for i in range(len(mat)): 
        mat[i] = int(input("Enter no "))
        
mat = mat.reshape(row,col)
print("matrix:\n",mat)
print("Transpose : \n", mat.T)
      
        

Enter number of rows:4
Enter number of col:5
Enter no 1
Enter no 2
Enter no 3
Enter no 5
Enter no 54
Enter no 45
Enter no 45
Enter no 56
Enter no 45
Enter no 56
Enter no 45
Enter no 45
Enter no 4556
Enter no 54
Enter no 4
Enter no 546
Enter no 45
Enter no 4
Enter no 54
Enter no 45
matrix:
 [[   1    2    3    5   54]
 [  45   45   56   45   56]
 [  45   45 4556   54    4]
 [ 546   45    4   54   45]]
Transpose : 
 [[   1   45   45  546]
 [   2   45   45   45]
 [   3   56 4556    4]
 [   5   45   54   54]
 [  54   56    4   45]]


In [59]:
M1.T.T

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [60]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [61]:
M1.T + M2.T, (M1 + M2).T

(array([[ 6,  2,  6],
        [10,  9,  6],
        [13, 16, 11]]),
 array([[ 6,  2,  6],
        [10,  9,  6],
        [13, 16, 11]]))

In [62]:
(M1 @ M2).T,  M2.T @ M1.T

(array([[44, 58, 48],
        [84, 54, 48],
        [81, 48, 38]]),
 array([[44, 58, 48],
        [84, 54, 48],
        [81, 48, 38]]))

## Trace of Matrix

In [63]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [64]:
add = 0
rn = 0

for row in M1:
    add = add + row[rn]
    rn += 1

In [65]:
add

13

In [66]:
np.trace(M1)

13

In [67]:
M3 = np.array([[3,4,8,0],[2,8,1,3],[1,9,5,6]],dtype=np.int8)

In [68]:
M3

array([[3, 4, 8, 0],
       [2, 8, 1, 3],
       [1, 9, 5, 6]], dtype=int8)

In [69]:
np.trace(M3)

16

In [70]:
np.trace(M1 @ M2), np.trace(M2 @ M1)

(136, 136)

In [71]:
np.trace(M1 ), np.trace(M1.T)

(13, 13)

In [72]:
2 * np.trace(M1), np.trace(2 * M1)

(26, 26)

In [73]:
np.trace(M1 + M2) , np.trace(M1) + np.trace(M2)

(26, 26)

## Determinant of matrix

In [74]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [75]:
np.linalg.det(M1)

-95.99999999999999

In [76]:
np.linalg.det(M2)

-133.99999999999997

### Inverse of the matrix


In [77]:
np.linalg.inv(M1)

array([[ 0.10416667,  0.29166667, -0.40625   ],
       [ 0.16666667, -0.33333333,  0.25      ],
       [-0.04166667,  0.08333333,  0.0625    ]])

### rank of matrix

In [79]:
M4 = np.array([[1,2],[2,4]])

In [80]:
M4

array([[1, 2],
       [2, 4]])

In [81]:
np.linalg.matrix_rank(M4)

1

In [83]:
M5 = np.array([[1,2],[3,4]])
np.linalg.matrix_rank(M5)

2

In [88]:
M4 = np.array([[1,2,3],[2,4,6],[1,3,4]])
np.linalg.matrix_rank(M4)


1

In [89]:
M4

array([[1. , 2. , 3. ],
       [2. , 4. , 6. ],
       [1.5, 3. , 4.5]])

In [90]:
M4 = np.array([[1,2,3],[2,4,6],[7,8,9]])
np.linalg.matrix_rank(M4)

2

### Row Matrix

In [91]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [118]:
R = M1.reshape(1,-1)

In [119]:
R.shape

(1, 9)

In [120]:
R

array([[4, 5, 6, 2, 1, 9, 0, 2, 8]])

### column Matrix

In [121]:
C = M1.reshape(-1,1)

In [122]:
C.shape

(9, 1)

In [123]:
C


array([[4],
       [5],
       [6],
       [2],
       [1],
       [9],
       [0],
       [2],
       [8]])

In [124]:
C.T

array([[4, 5, 6, 2, 1, 9, 0, 2, 8]])

In [125]:
R.T

array([[4],
       [5],
       [6],
       [2],
       [1],
       [9],
       [0],
       [2],
       [8]])

### Square Matrix

In [138]:

def isSquareMatrix(M):
    if M.shape[0] == M.shape[1]:
        return True
    else:
        return False
    
  

In [139]:
isSquareMatrix(M1)  

True

In [140]:
isSquareMatrix(M) 

False

In [150]:
S = np.zeros([4,4],dtype = np.int8)
S=S+4

In [151]:
S

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]], dtype=int8)

### Rectangular Matrix

In [153]:
def isSquareMatrix(M):
    if M.shape[0] != M.shape[1]:
        return True
    else:
        return False
    

In [160]:
S.shape

(4, 4)

In [161]:
isSquareMatrix(S)  

False

In [163]:
M.shape

(3, 4)

In [164]:
isSquareMatrix(M)

True

### Diagonal Matrix

In [185]:
S = np.zeros([4,4],dtype = np.int8)

In [186]:
S

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [187]:
for i in range(4):
    S[i][i] = 4
    
S
   

array([[4, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 4]], dtype=int8)

In [219]:
def isDiagonalMatrix(M):
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            if i != j and M[i][j] != 0:
                return False
    return True 

In [220]:
D[1][2] = 5
D

array([[4, 0, 0, 0],
       [0, 4, 5, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 4]], dtype=int8)

In [221]:
isDiagonalMatrix(D)

False

In [222]:
D = np.zeros([4,4],dtype = np.int8)
for i in range(4):
    D[i][i] = 4
    

    

 ### identity Matrix

In [196]:
I = np.zeros([4,4],dtype = np.int8)
for i in range(4):
    I[i][i] = 1
    
I 

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [223]:
np.diag(I)

array([1, 1, 1, 1], dtype=int8)

## Symmetric Matrix

In [271]:
M4 = np.array([[2,3,6],[3,4,5],[6,5,9]])

In [272]:
(M4 == M4.T).sum()

9

In [273]:
M4.size

9

In [277]:
def isSymmetricMatrix(M):
    if (M == t).sum()==M.size:
        return True
    else:
        return False

In [281]:
isSymmetricMatrix(M4)

True

In [282]:
isSymmetricMatrix(M1)

False

## Skew-Symmetric Matrix

In [283]:
S2 = np.array([[0,3],[-3,0]])

In [284]:
S2

array([[ 0,  3],
       [-3,  0]])

In [285]:
-S2

array([[ 0, -3],
       [ 3,  0]])

In [286]:
S2.T

array([[ 0, -3],
       [ 3,  0]])

In [287]:
S2.size

4

In [293]:
(-S2 == S2.T)

array([[ True,  True],
       [ True,  True]])

## Eigen Values and Vectors

In [301]:
A = np.array([[-6,3],[4,5]])

eigenvalues,eigenvectors = np.linalg.eig(A)

print("EigenValues:")
print(eigenvalues)

print("EigenVectors:")
print(eigenvectors)


EigenValues:
[-7.  6.]
EigenVectors:
[[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


In [302]:
A @ eigenvectors
    

array([[ 6.64078309, -1.45521375],
       [-2.21359436, -5.820855  ]])

In [303]:
eigenvalues * eigenvectors

array([[ 6.64078309, -1.45521375],
       [-2.21359436, -5.820855  ]])